"""Centralised supervisor agent.

The supervisor has a god's-eye view of all vehicle states (unlike the
individual vehicles which only see what their comms allows).  It uses this
privileged view to detect fleet-level anomalies that individual vehicles
cannot see and to issue corrective commands via the SimRunner.

DESIGN ASSUMPTIONS:
  S1. The supervisor is optional (``use_supervisor=False`` by default).
      Results with and without the supervisor are comparable, allowing
      A/B evaluation of centralised vs. decentralised coordination.
  S2. The supervisor does NOT override vehicle-level safety mechanisms.
      Its actions are advisory; if a vehicle is in BREAKDOWN it ignores
      supervisor commands.
  S3. The supervisor observes true positions, not estimated positions.
      In a real system a centralised supervisor would use fused data from
      all vehicles; this is an optimistic approximation.
  S4. Supervisor actions are logged at INFO severity.  No CRITICAL events
      are generated by the supervisor itself.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from convoy_commander.core.config import SimConfig
    from convoy_commander.core.world import World
    from convoy_commander.vehicles.vehicle import Vehicle


@dataclass
class SupervisorAction:
    """An advisory action produced by the supervisor."""

    action_type: str          # "replan" | "formation_alert" | "rescue"
    target_vehicle_id: int    # -1 = fleet-wide
    reason: str = ""
    details: dict = field(default_factory=dict)


class CentralSupervisor:
    """Fleet-wide monitoring and advisory coordination.

    The supervisor runs every simulation step (it is cheap — O(N^2) in the
    number of vehicles) and returns a list of ``SupervisorAction`` objects
    that the ``SimRunner`` may act upon.
    """

    # Thresholds
    STUCK_SPEED_THRESHOLD: float = 0.3       # m/s — below this, vehicle is "stuck"
    STUCK_STEPS_THRESHOLD: int = 200         # steps at stuck speed → ~20s at dt=0.1
    CONVOY_SPLIT_THRESHOLD: float = 350.0    # m — max operational spread before alert
    ISOLATION_TIMEOUT: float = 30.0          # s — last comms time for "isolated" check

    def __init__(self, config: SimConfig) -> None:
        self.config = config
        # Per-vehicle stuck-step counters
        self._stuck_steps: dict[int, int] = {}
        # Per-vehicle replan cooldown (avoid spamming replan)
        self._replan_cooldown: dict[int, float] = {}
        self._replan_cooldown_time: float = 30.0  # s between replans for same vehicle
        # Formation alert cooldown
        self._last_formation_alert: float = -999.0
        self._formation_alert_interval: float = 20.0

    def observe(
        self,
        vehicles: list[Vehicle],
        world: World,
        t: float,
    ) -> list[SupervisorAction]:
        """Run one supervisor tick.  Returns advisory actions (possibly empty)."""
        actions: list[SupervisorAction] = []

        operational = [v for v in vehicles if v.is_operational]
        if not operational:
            return actions

        # --- Detect stuck vehicles ---
        for v in operational:
            if v.state.speed < self.STUCK_SPEED_THRESHOLD:
                self._stuck_steps[v.id] = self._stuck_steps.get(v.id, 0) + 1
            else:
                self._stuck_steps[v.id] = 0

            if self._stuck_steps.get(v.id, 0) >= self.STUCK_STEPS_THRESHOLD:
                cooldown_until = self._replan_cooldown.get(v.id, -1.0)
                if t >= cooldown_until:
                    self._replan_cooldown[v.id] = t + self._replan_cooldown_time
                    self._stuck_steps[v.id] = 0
                    actions.append(SupervisorAction(
                        action_type="replan",
                        target_vehicle_id=v.id,
                        reason=f"Vehicle {v.id} stuck for >{self.STUCK_STEPS_THRESHOLD} "
                               f"steps (speed={v.state.speed:.2f}m/s)",
                    ))

        # --- Detect convoy split ---
        if len(operational) >= 2 and t - self._last_formation_alert >= self._formation_alert_interval:
            max_dist = 0.0
            worst_a, worst_b = operational[0].id, operational[1].id
            for i in range(len(operational)):
                for j in range(i + 1, len(operational)):
                    d = operational[i].state.distance_to(operational[j].state)
                    if d > max_dist:
                        max_dist = d
                        worst_a = operational[i].id
                        worst_b = operational[j].id
            if max_dist > self.CONVOY_SPLIT_THRESHOLD:
                self._last_formation_alert = t
                actions.append(SupervisorAction(
                    action_type="formation_alert",
                    target_vehicle_id=-1,
                    reason=f"Convoy spread={max_dist:.0f}m > threshold={self.CONVOY_SPLIT_THRESHOLD:.0f}m "
                           f"(worst pair V{worst_a}–V{worst_b})",
                    details={"max_spread_m": max_dist, "vehicle_a": worst_a, "vehicle_b": worst_b},
                ))

        # --- Detect isolated vehicles ---
        for v in operational:
            comms_gap = t - v.last_comms_time
            if comms_gap > self.ISOLATION_TIMEOUT and t > self.ISOLATION_TIMEOUT:
                cooldown_until = self._replan_cooldown.get(v.id, -1.0)
                if t >= cooldown_until:
                    self._replan_cooldown[v.id] = t + self._replan_cooldown_time
                    actions.append(SupervisorAction(
                        action_type="rescue",
                        target_vehicle_id=v.id,
                        reason=f"Vehicle {v.id} isolated: no comms for {comms_gap:.0f}s",
                        details={"comms_gap_s": comms_gap},
                    ))

        return actions
